name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git checkout -b site
          git add -f build
          git commit -m "Deploy website"
          git push origin site --force
          
      - name: Create deployment URL
        run: |
          echo "Your site is deployed at: https://raw.githubusercontent.com/Nitin-Pindoriya/my-docs/site/build/index.html"
          echo "To view the site, use: https://htmlpreview.github.io/?https://raw.githubusercontent.com/Nitin-Pindoriya/my-docs/site/build/index.html" 
